apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: gitea/manifests
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: gitea
    app.kubernetes.io/part-of: gitea
    apps.open-cluster-management.io/reconcile-rate: high
  name: gitea-subscription
  namespace: acmapp-gitea
spec:
  channel: acmapp-gitea/github-gitea-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: gitea-placement
  secondaryChannel: ""