apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitea-namespace.yaml
  - acmapp-gitea-namespace.yaml
  - gitea-channel.yaml
  - gitea-placementrule.yaml
  - gitea-subscription.yaml
  - gitea-application.yaml
